import Head from 'next/head'
import PaymentMethodList from '../../src/components/pageComponents/CompanyList/PaymentForm/PaymentMethod'
import IncomeTypeList from '../../src/components/pageComponents/IncomeTypeList';
import companies from '../../src/data/companies';
export default function PaymentMethods() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <IncomeTypeList />
        </div>
    )
}
