import Head from 'next/head'
import CompanyList from '../src/components/pageComponents/CompanyList'

export default function ClientPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CompanyList />
    </div>
  )
}
